sudo: required
services:
  - docker

before_install:
  - docker build -t kornvollis/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kornvollis/react-test npm test -- --coverage

after_success:
  - docker build -t kornvollis/multi-client ./client
  - docker build -t kornvollis/multi-nginx ./nginx
  - docker build -t kornvollis/multi-server ./server
  - docker build -t kornvollis/multi-worker ./worker
  # Log in to dokcer CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the images to docker hub  
  - docker push kornvollis/multi-client
  - docker push kornvollis/multi-nginx
  - docker push kornvollis/multi-server
  - docker push kornvollis/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-370470726063
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
